[mcp_servers.playwright-test]
command = "npx"
args = ["playwright", "run-test-mcp-server"]

[mcp_servers.angular-cli]
command = "npx"
args = ["-y", "@angular/cli@latest", "mcp", "-E", "modernize"]

[mcp_servers.git-grep]
url = "https://mcp.grep.app"

[features]
unified_exec = true
shell_snapshot = true
collab = true
steer = true
